name 'opentable/iis_rewrite'
version '0.0.1'
author 'opentable'
license 'MIT'
summary 'Module that will install the IIS Rewrite 2.0 Module on Windows'
project_page 'https://github.com/opentable/puppet-nsclient'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'opentable/download_file', '0.0.2'
dependency    'joshcooper/powershell', '0.0.6'
    